runtime: nodejs20
instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'bd-strapi'
  DATABASE_USER: 'user-strapi'
  DATABASE_PASSWORD: 'Pin2013'
  INSTANCE_CONNECTION_NAME: 'arquitectura-432900:us-central1:sql-strapi'
  GCS_BUCKET_NAME: 'bk-strapi-arqui'
  GCS_BASE_PATH: 'cms'

beta_settings:
  cloud_sql_instances: 'CLOUD_SQL_CONNECTION_NAME'
